/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   check_norris_loves_the_norminette.c                :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: chuck <chuck@student.42.fr>                +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2042/02/30 42:00:00 by chuck             #+#    #+#             */
/*   Updated: 2042/02/30 41:59:59 by chuck            ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "replies.h"
#include "client.h"

const t_reply	g_replies[] =
{
	{ true, "001", "RPL_WELCOME", 1, client_reply_print_all_params_to_home },
	{ true, "002", "RPL_YOURHOST", 1, client_reply_print_all_params_to_home },
	{ true, "003", "RPL_CREATED", 1, client_reply_print_all_params_to_home },
	{ true, "004", "RPL_MYINFO", 1, client_reply_print_all_params_to_home },
	{ true, "005", "RPL_BOUNCE", 1, client_reply_print_all_params_to_home },
	{ true, "401", "ERR_NOSUCHNICK", 2, client_reply_exec_default },
	{ true, "402", "ERR_NOSUCHSERVER", 2, client_reply_exec_default },
	{ true, "403", "ERR_NOSUCHCHANNEL", 2, client_reply_exec_default },
	{ true, "404", "ERR_CANNOTSENDTOCHAN", 2, client_reply_exec_default },
	{ true, "405", "ERR_TOOMANYCHANNELS", 2, client_reply_exec_default },
	{ true, "406", "ERR_WASNOSUCHNICK", 2, client_reply_exec_default },
	{ true, "407", "ERR_TOOMANYTARGETS", 2, client_reply_exec_default },
	{ true, "409", "ERR_NOORIGIN", 1, client_reply_exec_default },
	{ true, "411", "ERR_NORECIPIENT", 1, client_reply_exec_default },
	{ true, "412", "ERR_NOTEXTTOSEND", 1, client_reply_exec_default },
	{ true, "413", "ERR_NOTOPLEVEL", 2, client_reply_exec_default },
	{ true, "414", "ERR_WILDTOPLEVEL", 2, client_reply_exec_default },
	{ true, "421", "ERR_UNKNOWNCOMMAND", 2, client_reply_exec_default },
	{ true, "422", "ERR_NOMOTD", 1, client_reply_exec_default },
	{ true, "423", "ERR_NOADMININFO", 2, client_reply_exec_default },
	{ true, "424", "ERR_FILEERROR", 1, client_reply_exec_default },
	{ true, "431", "ERR_NONICKNAMEGIVEN", 1, client_reply_exec_default },
	{ true, "432", "ERR_ERRONEUSNICKNAME", 2, client_reply_exec_default },
	{ true, "433", "ERR_NICKNAMEINUSE", 2, client_reply_exec_default },
	{ true, "436", "ERR_NICKCOLLISION", 2, client_reply_exec_default },
	{ true, "441", "ERR_USERNOTINCHANNEL", 3, client_reply_exec_default },
	{ true, "442", "ERR_NOTONCHANNEL", 2, client_reply_exec_default },
	{ true, "443", "ERR_USERONCHANNEL", 3, client_reply_exec_default },
	{ true, "444", "ERR_NOLOGIN", 2, client_reply_exec_default },
	{ true, "445", "ERR_SUMMONDISABLED", 1, client_reply_exec_default },
	{ true, "446", "ERR_USERSDISABLED", 1, client_reply_exec_default },
	{ true, "451", "ERR_NOTREGISTERED", 1, client_reply_exec_default },
	{ true, "461", "ERR_NEEDMOREPARAMS", 2, client_reply_exec_default },
	{ true, "462", "ERR_ALREADYREGISTRED", 1, client_reply_exec_default },
	{ true, "463", "ERR_NOPERMFORHOST", 1, client_reply_exec_default },
	{ true, "464", "ERR_PASSWDMISMATCH", 1, client_reply_exec_default },
	{ true, "465", "ERR_YOUREBANNEDCREEP", 1, client_reply_exec_default },
	{ true, "467", "ERR_KEYSET", 2, client_reply_exec_default },
	{ true, "471", "ERR_CHANNELISFULL", 2, client_reply_exec_default },
	{ true, "472", "ERR_UNKNOWNMODE", 2, client_reply_exec_default },
	{ true, "473", "ERR_INVITEONLYCHAN", 2, client_reply_exec_default },
	{ true, "474", "ERR_BANNEDFROMCHAN", 2, client_reply_exec_default },
	{ true, "475", "ERR_BADCHANNELKEY", 2, client_reply_exec_default },
	{ true, "481", "ERR_NOPRIVILEGES", 1, client_reply_exec_default },
	{ true, "482", "ERR_CHANOPRIVSNEEDED", 2, client_reply_exec_default },
	{ true, "483", "ERR_CANTKILLSERVER", 1, client_reply_exec_default },
	{ true, "491", "ERR_NOOPERHOST", 1, client_reply_exec_default },
	{ true, "501", "ERR_UMODEUNKNOWNFLAG", 1, client_reply_exec_default },
	{ true, "502", "ERR_USERSDONTMATCH", 1, client_reply_exec_default },
	{ true, "300", "RPL_NONE", 0, client_reply_exec_default },
	{ true, "302", "RPL_USERHOST", 1, client_reply_exec_default },
	{ true, "303", "RPL_ISON", 1, client_reply_exec_default },
	{ true, "301", "RPL_AWAY", 2, client_reply_exec_default },
	{ true, "305", "RPL_UNAWAY", 1, client_reply_exec_default },
	{ true, "306", "RPL_NOWAWAY", 1, client_reply_exec_default },
	{ true, "311", "RPL_WHOISUSER", 5, client_reply_exec_default },
	{ true, "312", "RPL_WHOISSERVER", 3, client_reply_exec_default },
	{ true, "313", "RPL_WHOISOPERATOR", 2, client_reply_exec_default },
	{ true, "317", "RPL_WHOISIDLE", 3, client_reply_exec_default },
	{ true, "318", "RPL_ENDOFWHOIS", 2, client_reply_exec_default },
	{ true, "319", "RPL_WHOISCHANNELS", 2, client_reply_exec_default },
	{ true, "314", "RPL_WHOWASUSER", 5, client_reply_exec_default },
	{ true, "369", "RPL_ENDOFWHOWAS", 2, client_reply_exec_default },
	{ true, "321", "RPL_LISTSTART", 2, client_reply_exec_default },
	{ true, "322", "RPL_LIST", 3, client_reply_exec_default },
	{ true, "323", "RPL_LISTEND", 1, client_reply_exec_default },
	{ true, "324", "RPL_CHANNELMODEIS", 3, client_reply_exec_default },
	{ true, "331", "RPL_NOTOPIC", 2, client_reply_topic },
	{ true, "332", "RPL_TOPIC", 2, client_reply_topic },
	{ true, "341", "RPL_INVITING", 2, client_reply_exec_default },
	{ true, "342", "RPL_SUMMONING", 2, client_reply_exec_default },
	{ true, "351", "RPL_VERSION", 4, client_reply_exec_default },
	{ true, "352", "RPL_WHOREPLY", 7, client_reply_exec_default },
	{ true, "315", "RPL_ENDOFWHO", 2, client_reply_exec_default },
	{ true, "353", "RPL_NAMREPLY", 2, client_reply_get_users },
	{ true, "366", "RPL_ENDOFNAMES", 2, client_reply_get_users },
	{ true, "364", "RPL_LINKS", 3, client_reply_exec_default },
	{ true, "365", "RPL_ENDOFLINKS", 2, client_reply_exec_default },
	{ true, "367", "RPL_BANLIST", 2, client_reply_exec_default },
	{ true, "368", "RPL_ENDOFBANLIST", 2, client_reply_exec_default },
	{ true, "371", "RPL_INFO", 1, client_reply_exec_default },
	{ true, "374", "RPL_ENDOFINFO", 1, client_reply_exec_default },
	{ true, "375", "RPL_MOTDSTART", 1, client_reply_print_all_params_to_home },
	{ true, "372", "RPL_MOTD", 1, client_reply_print_all_params_to_home },
	{ true, "376", "RPL_ENDOFMOTD", 1, client_reply_print_all_params_to_home },
	{ true, "381", "RPL_YOUREOPER", 1, client_reply_exec_default },
	{ true, "382", "RPL_REHASHING", 2, client_reply_exec_default },
	{ true, "391", "RPL_TIME", 2, client_reply_exec_default },
	{ true, "392", "RPL_USERSSTART", 1, client_reply_exec_default },
	{ true, "393", "RPL_USERS", 1, client_reply_exec_default },
	{ true, "394", "RPL_ENDOFUSERS", 1, client_reply_exec_default },
	{ true, "395", "RPL_NOUSERS", 1, client_reply_exec_default },
	{ true, "200", "RPL_TRACELINK", 4, client_reply_exec_default },
	{ true, "201", "RPL_TRACECONNECTING", 3, client_reply_exec_default },
	{ true, "202", "RPL_TRACEHANDSHAKE", 3, client_reply_exec_default },
	{ true, "203", "RPL_TRACEUNKNOWN", 3, client_reply_exec_default },
	{ true, "204", "RPL_TRACEOPERATOR", 3, client_reply_exec_default },
	{ true, "205", "RPL_TRACEUSER", 3, client_reply_exec_default },
	{ true, "206", "RPL_TRACESERVER", 6, client_reply_exec_default },
	{ true, "208", "RPL_TRACENEWTYPE", 3, client_reply_exec_default },
	{ true, "261", "RPL_TRACELOG", 3, client_reply_exec_default },
	{ true, "211", "RPL_STATSLINKINFO", 7, client_reply_exec_default },
	{ true, "212", "RPL_STATSCOMMANDS", 2, client_reply_exec_default },
	{ true, "213", "RPL_STATSCLINE", 6, client_reply_exec_default },
	{ true, "214", "RPL_STATSNLINE", 6, client_reply_exec_default },
	{ true, "215", "RPL_STATSILINE", 6, client_reply_exec_default },
	{ true, "216", "RPL_STATSKLINE", 6, client_reply_exec_default },
	{ true, "218", "RPL_STATSYLINE", 5, client_reply_exec_default },
	{ true, "219", "RPL_ENDOFSTATS", 2, client_reply_exec_default },
	{ true, "241", "RPL_STATSLLINE", 5, client_reply_exec_default },
	{ true, "242", "RPL_STATSUPTIME", 1, client_reply_exec_default },
	{ true, "243", "RPL_STATSOLINE", 4, client_reply_exec_default },
	{ true, "244", "RPL_STATSHLINE", 4, client_reply_exec_default },
	{ true, "221", "RPL_UMODEIS", 1, client_reply_exec_default },
	{ true, "251", "RPL_LUSERCLIENT", 1,
		client_reply_print_all_params_to_home },
	{ true, "252", "RPL_LUSEROP", 2, client_reply_print_all_params_to_home },
	{ true, "253", "RPL_LUSERUNKNOWN", 2, client_reply_exec_default },
	{ true, "254", "RPL_LUSERCHANNELS", 2,
		client_reply_print_all_params_to_home },
	{ true, "255", "RPL_LUSERME", 1, client_reply_print_all_params_to_home },
	{ true, "256", "RPL_ADMINME", 2, client_reply_exec_default },
	{ true, "257", "RPL_ADMINLOC1", 1, client_reply_exec_default },
	{ true, "258", "RPL_ADMINLOC2", 1, client_reply_exec_default },
	{ true, "259", "RPL_ADMINEMAIL", 1, client_reply_exec_default },
	{ false, "ADMIN", NULL, 1, client_reply_exec_default },
	{ false, "AWAY", NULL, 1, client_reply_exec_default },
	{ false, "CONNECT", NULL, 3, client_reply_exec_default },
	{ false, "ERROR", NULL, 1, client_reply_exec_default },
	{ false, "INFO", NULL, 1, client_reply_exec_default },
	{ false, "INVITE", NULL, 2, client_reply_exec_default },
	{ false, "ISON", NULL, 255, client_reply_exec_default },
	{ false, "JOIN", NULL, 2, client_reply_join },
	{ false, "KICK", NULL, 3, client_reply_exec_default },
	{ false, "KILL", NULL, 2, client_reply_exec_default },
	{ false, "LINKS", NULL, 2, client_reply_exec_default },
	{ false, "LIST", NULL, 2, client_reply_exec_default },
	{ false, "MODE", NULL, 10, client_reply_exec_default },
	{ false, "NAMES", NULL, 1, client_reply_exec_default },
	{ false, "NICK", NULL, 1, client_reply_exec_default },
	{ false, "NOTICE", NULL, 2, client_reply_exec_default },
	{ false, "OPER", NULL, 2, client_reply_exec_default },
	{ false, "PART", NULL, 2, client_reply_part },
	{ false, "PASS", NULL, 1, client_reply_exec_default },
	{ false, "PING", NULL, 1, client_reply_ping },
	{ false, "PONG", NULL, 1, client_reply_exec_default },
	{ false, "PRIVMSG", NULL, 2, client_reply_privmsg },
	{ false, "QUIT", NULL, 1, client_reply_exec_default },
	{ false, "REHASH", NULL, 0, client_reply_exec_default },
	{ false, "RESTART", NULL, 0, client_reply_exec_default },
	{ false, "SERVER", NULL, 3, client_reply_exec_default },
	{ false, "SQUIT", NULL, 2, client_reply_exec_default },
	{ false, "STATS", NULL, 2, client_reply_exec_default },
	{ false, "SUMMON", NULL, 2, client_reply_exec_default },
	{ false, "TIME", NULL, 1, client_reply_exec_default },
	{ false, "TOPIC", NULL, 2, client_reply_topic },
	{ false, "TRACE", NULL, 1, client_reply_exec_default },
	{ false, "USER", NULL, 4, client_reply_exec_default },
	{ false, "USERHOST", NULL, 2, client_reply_exec_default },
	{ false, "USERS", NULL, 1, client_reply_exec_default },
	{ false, "VERSION", NULL, 1, client_reply_exec_default },
	{ false, "WALLOPS", NULL, 1, client_reply_exec_default },
	{ false, "WHO", NULL, 0, client_reply_exec_default },
	{ false, "WHOIS", NULL, 255, client_reply_exec_default },
	{ false, "WHOWAS", NULL, 3, client_reply_exec_default },
	{ false, NULL, NULL, 0, client_reply_exec_default }
};
